# Generated by Django 3.2 on 2024-09-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='UserInfo',
        ),
    ]
